#!/bin/bash

export AUTHOR_TESTING=1

for dir in MaxMind-DB-Common MaxMind-DB-Reader MaxMind-DB-Writer; do
    if [ -d "$dir/t" ]; then
        pushd $dir
        prove -I ../lib -I ../MaxMind-DB-Common/lib -I ../MaxMind-DB-Reader/lib -I ../MaxMind-DB-Writer/lib -lr -j 4 t/
        popd
    fi
done
