#!/bin/bash

for dir in MaxMind-IPDB-Common MaxMind-IPDB-Reader MaxMind-IPDB-Writer; do
    if [ -d "$dir/t" ]; then
        pushd $dir
        prove -I ../lib -I ../MaxMind-IPDB-Common/lib -I ../MaxMind-IPDB-Reader/lib -I ../MaxMind-IPDB-Writer/lib -lr -j 4 t/
        popd
    fi
done
