#!/bin/bash

set -e
set -u

git clean -dxf
export LOCALLIB=$HOME/local-lib/MaxMind-DB-perl
export PERL5LIB=$LOCALLIB/lib/perl5:$LOCALLIB/lib/perl5/x86_64-linux

BINDIR=`mm-perl -MConfig -e 'print $Config{bin}'`
DIRS="MaxMind-DB-Common MaxMind-DB-Reader MaxMind-DB-Writer"

$BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB TAP::Harness::JUnit Dist::Zilla

for dir in $DIRS; do
    pushd $dir
    if [ -f dist.ini ]; then
        $LOCALLIB/bin/dzil authordeps | $BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB
        $LOCALLIB/bin/dzil listdeps \
            | grep -v '^MaxMind::DB' | grep -v 'Test::MaxMind::DB' \
            | $BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB
    fi
    popd

    export PERL5LIB=$PERL5LIB:`pwd`/$dir/lib
done

last_exit=0
for dir in $DIRS; do
    pushd $dir
    if [ -d t ]; then
        export JUNIT_OUTPUT_FILE=`pwd`/junit_output.xml

        unset -e
        $BINDIR/perl $BINDIR/prove --harness=TAP::Harness::JUnit -r -j 2
        if [ "$?" -ne 0 ]; do
            last_exit=$?
        fi
        set -e
    fi
    popd
done

exit $last_exit
