#!/bin/bash

git clean -dxf
export LOCALLIB=$HOME/local-lib/MaxMind-DB-perl
export PERL5LIB=$LOCALLIB/lib/perl5:$LOCALLIB/lib/perl5/x86_64-linux

BINDIR=`mm-perl -MConfig -e 'print $Config{bin}'`
DIRS="MaxMind-DB-Common MaxMind-DB-Reader MaxMind-DB-Writer"

$BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB TAP::Harness::JUnit Dist::Zilla

for dir in $DIRS; do
    pushd $dir
    if [ -f dist.ini ]; then
        $BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB `$LOCALLIB/bin/dzil authordeps`
        $BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB `$LOCALLIB/bin/dzil listdeps`
    fi
    popd

    export PERL5LIB=$PERL5LIB:`pwd`/$dir/lib
done

for dir in $DIRS; do
    pushd $dir
    if [ -d t ]; then
        export JUNIT_OUTPUT_FILE=`pwd`/junit_output.xml
        $BINDIR/perl $BINDIR/prove --harness=TAP::Harness::JUnit -r -j 2
    fi
    popd
done
